
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[278] =
    {   0,
       46,   46,   55,   53,   54,   53,   54,   44,   53,   54,
       53,   54,   44,   53,   54,   23,   53,   54,   44,   53,
       54,   53,   54,   53,   54,   44,   53,   54,   44,   53,
       54,   27,   53,   54,   53,   54,   45,   53,   54,   53,
       54,   53,   54,   51,   53,   54,   50,   53,   54,   51,
       53,   54,   53,   54,   50,   53,   54,   53,   54,   53,
       54,   53,   54,   53,   54,   53,   54,   53,   54,   53,
       54,   53,   54,   33,   53,   54,   37,   53,   54,   37,
       53,   54,   35,   53,   54,   34,   53,   54,   53,   54,
       53,   54,   53,   54,   40,   53,   54,   53,   54,   53,

       54,   40,   53,   54,   40,   53,   54,   53,   54,   53,
       54,   53,   54,   53,   54,   53,   54,   53,   54,   46,
       53,   54,   53,   54,   21,   53,   54,    7,   53,   54,
       11,   53,   54,   15,   53,   54,   19,   53,   54,    3,
       53,   54,   53,   54,   53,   54,   53,   54,   53,   54,
       53,   54,   44,   44,   44,   44,   44,   27,   23,   39,
       39,   39,   44,   44,   27,   45,   48,   51,   51,   33,
       36,   35,   34,   40,   41,   41,   41,   40,   47,   46,
       22,   21,   32,   44,    1,   43,   44,   44,   43,   44,
       39,   51,    5,   29,    9,   31,   38,   41,   13,   41,

       17,    8,   16,   12,   20,    4,   44,   43,   43,   44,
       43,   44,   43,   44,    2,   49,   51,    6,   52,   10,
       14,   18,   44,   44,   44,   44,   44,   43,   43,   43,
       44,   43,   44,   51,   51,   28,   30,   42,   39,   39,
       39,   44,   44,   43,   43,   44,   24,   24,   32,   43,
       44,   44,   43,   44,   39,   25,   43,   43,   44,   43,
       44,   43,   44,   43,   43,   43,   44,   43,   44,   43,
       43,   44,   41,   41,   41,   26,   41
    } ;

static const flex_int16_t yy_accept[321] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    6,    8,   11,   13,   16,   19,
       22,   24,   26,   29,   32,   35,   37,   40,   42,   44,
       47,   50,   53,   55,   58,   60,   62,   64,   66,   68,
       70,   72,   74,   77,   80,   83,   86,   89,   91,   93,
       95,   98,  100,  102,  105,  108,  110,  112,  114,  116,
      118,  120,  123,  125,  128,  131,  134,  137,  140,  143,

      145,  147,  149,  151,  153,  153,  153,  154,  155,  156,
      156,  156,  157,  158,  159,  159,  160,  161,  161,  162,
      164,  165,  165,  166,  166,  167,  167,  168,  169,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  171,  172,  173,  174,  174,  174,
      174,  174,  174,  174,  174,  175,  176,  177,  178,  178,
      179,  179,  179,  179,  180,  181,  182,  183,  183,  183,
      183,  183,  183,  183,  184,  185,  186,  186,  186,  187,
      188,  189,  191,  192,  192,  192,  192,  193,  194,  195,
      195,  195,  195,  195,  196,  197,  197,  197,  197,  198,

      198,  198,  199,  200,  201,  201,  202,  202,  203,  204,
      205,  206,  207,  207,  208,  208,  209,  210,  211,  213,
      215,  216,  216,  217,  218,  218,  219,  219,  220,  220,
      221,  221,  221,  221,  222,  223,  223,  223,  223,  224,
      225,  226,  226,  226,  227,  228,  229,  230,  232,  234,
      234,  234,  234,  235,  236,  237,  238,  239,  239,  239,
      239,  240,  240,  241,  243,  244,  244,  245,  247,  247,
      247,  248,  250,  250,  250,  251,  252,  253,  255,  256,
      257,  257,  257,  257,  258,  259,  260,  262,  264,  264,
      264,  265,  266,  268,  270,  270,  270,  270,  270,  270,

      270,  271,  273,  273,  274,  275,  276,  276,  277,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    9,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   20,    1,
       21,   22,   23,    1,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       24,    1,   25,    9,   26,    1,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,    9,    9,    9,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[27] =
    {   0,
        1,    2,    3,    3,    4,    5,    6,    7,    5,    8,
        9,    9,   10,   11,   12,   13,   14,   15,   16,   14,
        1,   17,    1,    1,    1,   18
    } ;

static const flex_int16_t yy_base[356] =
    {   0,
        0,    0,   22,   37,   56,    0,   81,    0,  104,  120,
        0,    0,   24,   27,  136,    0,  157,    0,    0,    0,
       25,   26,  178,    0,  620,  617,  616,  613,  611,  608,
      604,  603,  616,  613,  612,  608,  604,  603,  602,  599,
      598,  594,  604,  923,   33,  202,  577,    0,  592,  221,
       31,  594,   34,   32,  591,    0,    0,   86,  592,   87,
      569,  590,  578,  923,    0,  564,  583,  560,  570,    0,
      556,  578,    0,  923,  577,  563,  557,  573,  236,  551,
        0,   41,  569,  566,   36,    0,  543,  561,   76,    0,
      562,  554,  558,    0,  923,  923,  923,  923,  923,    0,

        0,    0,    0,    0,   94,  554,   95,    0,    0,   85,
      551,    0,    0,  550,    0,  546,   96,   97,  548,  535,
       99,  544,  543,  522,    0,  101,  540,  111,  540,    0,
      528,  112,  515,  513,  116,  534,    0,  524,  124,  511,
      508,  128,    0,    0,  923,  517,  511,  525,  520,  519,
      518,  515,  108,    0,    0,  514,  510,  509,  508,    0,
      487,    0,  486,  923,  501,  923,    0,  495,  494,  493,
      490,  489,  143,  923,  151,    0,  106,  152,  153,  154,
      493,  492,  489,  481,  159,  487,  166,    0,  923,  474,
      475,  459,  480,    0,  923,  469,  470,  453,  923,  475,

      472,  469,    0,  465,  458,    0,  457,  923,  923,  923,
      923,  923,  172,  254,  173,  174,  179,  449,  459,  455,
      923,  193,  923,  275,  446,  923,  430,  923,  442,  923,
      426,    0,  445,  923,  923,  194,  206,  198,  397,  292,
      309,  327,  214,  164,  203,  223,  224,  218,  394,  228,
      240,  244,  393,  249,  923,  923,  923,  389,  388,  375,
      360,  230,  234,  310,  311,  312,  361,  343,  336,  274,
      273,  316,  317,  328,  329,  319,  331,  332,  333,  318,
      252,  347,  338,  340,  345,  339,  349,  351,  355,  363,
      356,  357,  358,  359,  379,  234,  367,  376,  381,  383,

      383,  227,  202,  385,  399,  401,  403,  196,  405,  186,
      170,  149,  139,  132,  127,  113,   79,  407,  923,  412,
      430,  445,  459,  472,  487,  500,  514,  527,  542,  556,
      569,  581,  590,  604,  618,  631,  644,  659,  674,  689,
      704,  719,  732,  745,  761,  776,  789,  802,  815,  830,
      843,  860,  875,  891,  906
    } ;

static const flex_int16_t yy_def[356] =
    {   0,
      319,    1,  320,  320,  319,    5,  320,    7,  320,  320,
      320,  320,  321,  321,  320,   15,   15,   17,  320,  320,
      320,  320,  320,   23,   23,   23,   23,   23,   23,   23,
       23,   23,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  319,  319,  319,  319,  319,  322,  319,  322,
      319,  319,  322,   50,  319,  323,  324,  319,  319,  325,
      319,  325,  326,  319,  327,  328,  319,  319,  329,  330,
      331,  319,  332,  319,  319,  319,  319,  319,  319,  319,
      333,  329,  319,  333,  333,  334,  319,  319,  319,  335,
      319,  319,  319,  336,  319,  319,  319,  319,  319,  337,

      338,  339,  340,  341,  319,  319,   46,  322,   50,  319,
      319,   53,   54,  319,  342,  319,  319,  319,  319,   53,
       53,  319,  319,  323,  324,  319,  319,  325,  325,  343,
      326,  319,  327,  328,  319,  319,  344,  329,  319,  330,
      331,  319,  345,  332,  319,  319,  319,  319,   79,  319,
      319,  319,  319,  346,  333,  138,  319,  319,  319,   85,
      334,  347,  335,  319,  319,  319,  336,  337,  338,  339,
      340,  341,  319,  319,   46,  342,  319,  319,  319,   53,
      180,  121,  319,  319,  319,  319,  325,  343,  319,  348,
      319,  349,  319,  344,  319,  350,  319,  351,  319,  319,

       79,  319,  346,  319,  319,  347,  319,  319,  319,  319,
      319,  319,  352,  319,  319,  319,  319,  180,  180,  180,
      319,  353,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  354,   79,  319,  319,  352,  352,  352,  214,  319,
      240,  352,  242,  240,  241,  319,  319,  180,  248,  353,
      353,  353,  224,  224,  319,  319,  319,   79,  319,  319,
      242,  242,  242,  240,  240,  242,  319,  248,  319,   79,
      319,  319,  242,  242,  242,  240,  240,  240,  242,  319,
       79,  319,  242,  242,  242,  240,  240,  240,  319,  355,
      242,  242,  240,  240,  355,  355,  355,  355,  355,  355,

      242,  240,  319,  355,  355,  355,  355,  319,  355,  319,
      319,  319,  319,  319,  319,  319,  355,  355,    0,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319
    } ;

static const flex_int16_t yy_nxt[950] =
    {   0,
       44,   45,   44,   44,   46,   47,   48,   49,   44,   50,
       48,   48,   51,   52,   48,   53,   44,   44,   54,   44,
       44,   55,   44,   56,   44,   44,   57,   75,   91,   91,
       75,   57,   92,   92,  105,  117,   57,  105,  120,   76,
       57,   57,   76,  118,   77,  156,   57,   77,  122,  121,
      113,   57,  159,  139,  160,   57,   44,   58,   44,   59,
       60,   61,   62,   44,   44,   62,   62,   62,   63,   44,
       62,   62,   64,   44,   62,   64,   44,   44,   64,   65,
       44,   66,   58,  318,   67,   58,   68,  126,  126,  117,
      126,  128,  159,   69,  153,  173,  173,  118,  173,  175,

      117,  178,  185,  181,   70,  185,   71,   72,  177,  179,
      215,   73,  185,   73,  182,  187,  190,  317,  216,   73,
      192,  190,   73,   72,  159,  192,  153,   73,  196,   73,
      190,  316,  198,  196,  192,   73,  315,  198,   73,   78,
       79,   80,  196,  314,  213,   81,  198,  213,   82,   83,
       81,   84,  213,  313,   85,  214,  178,  217,  218,   86,
      222,   71,   87,  222,  216,  179,   44,  222,  264,  219,
      224,   44,   88,  236,  312,   89,  237,  215,  247,  265,
       90,   93,   94,  217,   94,  246,  216,   94,   94,   94,
      311,  216,   94,   94,  250,  236,   94,  251,  237,  319,

      310,  259,   95,  105,  308,  106,  107,  236,  108,  259,
      237,  109,  108,  108,  110,  111,  108,  112,  263,  266,
      113,  245,  268,  114,  106,  109,  238,  267,  247,  250,
      109,  302,  251,  248,  274,  246,  246,  303,  263,  109,
      149,  250,  275,  269,  251,  319,  238,  269,  150,  151,
      319,  152,  269,  254,  153,  236,  290,  106,  239,  238,
      240,  238,  238,  241,  240,  240,  242,  243,  240,  244,
      238,  238,  245,  238,  282,  114,  250,  282,  281,  253,
      252,  254,  252,  252,  254,  254,  254,  252,  252,  254,
      254,  252,  252,  254,  252,  259,  240,  238,  240,  238,

      238,  240,  240,  240,  238,  238,  240,  240,  238,  238,
      240,  238,  260,  241,  264,  277,  279,  282,  241,  289,
      282,  283,  289,  286,  238,  276,  278,  241,  319,  284,
      259,  261,  274,  285,  287,  277,  288,  279,  280,  262,
      284,  275,  283,  286,  292,  238,  287,  278,  105,  285,
      291,  105,  284,  294,  293,  288,  126,  284,  108,  126,
      301,  292,  302,  294,  287,  267,  287,  295,  291,  291,
      303,  304,  273,  293,  293,  297,  298,  272,  299,  303,
      305,  300,  303,  295,  303,  306,  303,  301,  303,  304,
      271,  297,  298,  270,  299,  238,  269,  300,  249,  307,

      260,  300,  303,  305,  303,  306,  303,  309,  303,  309,
      303,  318,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,  108,  258,
      108,  256,  108,  108,  256,  255,  108,  108,  255,  220,
      108,  124,  124,  249,  248,  124,  124,  235,  234,  204,
      124,  124,  124,  202,  124,  125,  233,  232,  231,  125,
      230,  229,  228,  125,  227,  226,  225,  125,  129,  223,
      129,  221,  129,  183,  129,  129,  220,  181,  129,  129,

      212,  211,  129,  131,  210,  209,  208,  131,  165,  131,
      207,  205,  204,  158,  157,  131,  133,  133,  156,  158,
      133,  133,  157,  202,  201,  133,  133,  133,  200,  133,
      134,  147,  146,  195,  134,  197,  195,  193,  189,  191,
      189,  319,  134,  186,  134,  138,  184,  123,  183,  138,
      180,  138,  119,  116,  123,  119,  174,  138,  140,  140,
      166,  165,  140,  140,  164,  158,  162,  140,  140,  140,
      158,  140,  141,  157,  154,  148,  141,  147,  146,  145,
      143,  142,  139,  137,  141,  136,  141,  144,  144,  135,
      132,  319,  130,  144,  127,  123,  144,  155,  119,  116,

      115,  155,  155,  319,  104,  155,  161,  161,  104,  103,
      161,  161,  103,  102,  102,  161,  161,  161,  101,  161,
      163,  163,  101,  100,  163,  163,  100,   99,   99,  163,
      163,  163,   98,  163,  167,   98,  167,   97,  167,  167,
       97,   96,  167,  167,   96,  319,  167,  168,  319,  168,
      168,  168,  319,  319,  319,  168,  168,  168,  168,  168,
      319,  168,  169,  319,  169,  169,  169,  319,  319,  319,
      169,  169,  169,  169,  169,  319,  169,  170,  319,  170,
      170,  170,  319,  319,  319,  170,  170,  170,  170,  170,
      319,  170,  171,  319,  171,  171,  171,  319,  319,  319,

      171,  171,  171,  171,  171,  319,  171,  172,  319,  172,
      172,  172,  319,  319,  319,  172,  172,  172,  172,  172,
      319,  172,  176,  319,  319,  176,  176,  319,  319,  319,
      176,  176,  176,  319,  176,  188,  319,  319,  188,  188,
      319,  319,  319,  188,  188,  188,  319,  188,  194,  319,
      319,  194,  194,  319,  319,  319,  194,  194,  194,  319,
      194,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  319,  199,  203,
      319,  319,  203,  203,  319,  319,  319,  203,  203,  203,
      319,  203,  206,  319,  319,  206,  206,  319,  319,  319,

      206,  206,  206,  319,  206,  190,  319,  319,  319,  190,
      319,  190,  319,  319,  319,  319,  319,  190,  192,  319,
      319,  319,  192,  319,  319,  319,  319,  319,  319,  319,
      192,  319,  192,  196,  319,  319,  319,  196,  319,  196,
      319,  319,  319,  319,  319,  196,  198,  319,  319,  319,
      198,  319,  319,  319,  319,  319,  319,  319,  198,  319,
      198,  238,  319,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  252,  319,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  257,  319,  257,  319,  257,  257,  257,  257,  257,

      319,  319,  257,  257,  257,  257,  319,  257,  257,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,   43,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319
    } ;

static const flex_int16_t yy_chk[950] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,   13,   21,   22,
       14,    3,   21,   22,   45,   51,    3,   45,   53,   13,
        3,    4,   14,   51,   13,   82,    4,   14,   54,   53,
       54,    4,   85,   82,   85,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    7,  317,    7,    7,    7,   58,   60,  110,
       58,   60,   89,    7,   89,  105,  107,  110,  105,  107,

      117,  118,  126,  121,    7,  126,    7,    9,  117,  118,
      177,    9,  128,    9,  121,  128,  132,  316,  177,    9,
      135,  132,    9,   10,  153,  135,  153,   10,  139,   10,
      132,  315,  142,  139,  135,   10,  314,  142,   10,   15,
       15,   15,  139,  313,  173,   15,  142,  173,   15,   15,
       15,   15,  175,  312,   15,  175,  178,  179,  180,   15,
      185,   15,   17,  185,  178,  179,   17,  187,  244,  180,
      187,   17,   17,  213,  311,   17,  213,  215,  216,  244,
       17,   23,   23,  217,   23,  215,  216,   23,   23,   23,
      310,  217,   23,   23,  222,  236,   23,  222,  236,  238,

      308,  238,   23,   46,  303,   46,   46,  237,   46,  237,
      237,   46,   46,   46,   46,   46,   46,   46,  243,  245,
       46,  245,  248,   46,   50,   50,  243,  246,  247,  250,
       50,  302,  250,  248,  262,  246,  247,  296,  263,   50,
       79,  251,  262,  251,  251,  252,  263,  252,   79,   79,
      254,   79,  254,  254,   79,  214,  281,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  271,  214,  224,  271,  270,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  240,  240,  240,  240,  240,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  241,  241,  264,  265,  266,  272,  241,  280,
      272,  273,  280,  276,  266,  264,  265,  241,  242,  273,
      242,  242,  274,  275,  276,  277,  278,  279,  269,  242,
      274,  275,  283,  286,  284,  279,  277,  278,  282,  285,
      283,  282,  284,  287,  286,  288,  289,  285,  268,  289,
      291,  292,  293,  294,  287,  267,  288,  290,  291,  292,
      297,  297,  261,  293,  294,  290,  290,  260,  290,  298,
      298,  290,  295,  295,  299,  299,  300,  301,  304,  304,
      259,  295,  295,  258,  295,  301,  253,  295,  249,  300,

      239,  300,  305,  305,  306,  306,  307,  307,  309,  309,
      318,  318,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  322,  233,
      322,  231,  322,  322,  229,  227,  322,  322,  225,  220,
      322,  323,  323,  219,  218,  323,  323,  207,  205,  204,
      323,  323,  323,  202,  323,  324,  201,  200,  198,  324,
      197,  196,  193,  324,  192,  191,  190,  324,  325,  186,
      325,  184,  325,  183,  325,  325,  182,  181,  325,  325,

      172,  171,  325,  326,  170,  169,  168,  326,  165,  326,
      163,  161,  159,  158,  157,  326,  327,  327,  156,  152,
      327,  327,  151,  150,  149,  327,  327,  327,  148,  327,
      328,  147,  146,  141,  328,  140,  138,  136,  134,  133,
      131,  129,  328,  127,  328,  329,  124,  123,  122,  329,
      120,  329,  119,  116,  114,  111,  106,  329,  330,  330,
       93,   92,  330,  330,   91,   88,   87,  330,  330,  330,
       84,  330,  331,   83,   80,   78,  331,   77,   76,   75,
       72,   71,   69,   68,  331,   67,  331,  332,  332,   66,
       63,   62,   61,  332,   59,   55,  332,  333,   52,   49,

       47,  333,  333,   43,   42,  333,  334,  334,   41,   40,
      334,  334,   39,   38,   37,  334,  334,  334,   36,  334,
      335,  335,   35,   34,  335,  335,   33,   32,   31,  335,
      335,  335,   30,  335,  336,   29,  336,   28,  336,  336,
       27,   26,  336,  336,   25,    0,  336,  337,    0,  337,
      337,  337,    0,    0,    0,  337,  337,  337,  337,  337,
        0,  337,  338,    0,  338,  338,  338,    0,    0,    0,
      338,  338,  338,  338,  338,    0,  338,  339,    0,  339,
      339,  339,    0,    0,    0,  339,  339,  339,  339,  339,
        0,  339,  340,    0,  340,  340,  340,    0,    0,    0,

      340,  340,  340,  340,  340,    0,  340,  341,    0,  341,
      341,  341,    0,    0,    0,  341,  341,  341,  341,  341,
        0,  341,  342,    0,    0,  342,  342,    0,    0,    0,
      342,  342,  342,    0,  342,  343,    0,    0,  343,  343,
        0,    0,    0,  343,  343,  343,    0,  343,  344,    0,
        0,  344,  344,    0,    0,    0,  344,  344,  344,    0,
      344,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,    0,  345,  346,
        0,    0,  346,  346,    0,    0,    0,  346,  346,  346,
        0,  346,  347,    0,    0,  347,  347,    0,    0,    0,

      347,  347,  347,    0,  347,  348,    0,    0,    0,  348,
        0,  348,    0,    0,    0,    0,    0,  348,  349,    0,
        0,    0,  349,    0,    0,    0,    0,    0,    0,    0,
      349,    0,  349,  350,    0,    0,    0,  350,    0,  350,
        0,    0,    0,    0,    0,  350,  351,    0,    0,    0,
      351,    0,    0,    0,    0,    0,    0,    0,  351,    0,
      351,  352,    0,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  353,    0,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  354,    0,  354,    0,  354,  354,  354,  354,  354,

        0,    0,  354,  354,  354,  354,    0,  354,  354,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fisierTest.l"
#line 2 "fisierTest.l"
#include <iostream>
#include <fstream>
#include <string>
using namespace std;

int count = 0, linkValue = 0;
int wordListCounter = 3, blockquote = 5;
char STXTitle[101];
#line 809 "lex.yy.c"

#line 811 "lex.yy.c"

#define INITIAL 0
#define IDENTATION 1
#define PARAGRAPH 2
#define IMPORTANT 3
#define QUOTE 4
#define NOT_FIRST_WORD 5
#define CHECK_TITLE 6
#define LIST 7
#define LIST_IMPORTANT 8
#define CHECK_LINK 9
#define SKIP_ATX_ENDING 10
#define LINK_PARA 11
#define LINK_IMP 12
#define LINK_LIST 13
#define LINK_LIST_IMP 14
#define LINK_INITIAL 15
#define SKIP_END_LINK_PARAGRAPH 16
#define SKIP_END_LINK_LIST 17
#define SKIP_END_LINK_IMPORTANT 18
#define SKIP_END_LINK_LIST_IMPORTANT 19
#define SKIP_END_LINK_INITIAL 20

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 37 "fisierTest.l"

#line 1056 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 320 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 923 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];

find_rule: /* we branch to this label when backing up */

		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 38 "fisierTest.l"
{
    for (int i = 1; i <= 3 * count; i++) {
        cout << " ";
    }
    cout << yytext[1] << yytext[0] << yytext + 2;
    BEGIN (LINK_INITIAL);
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 45 "fisierTest.l"
{
    for (int i = 1; i <= 3 * count; i++) {
        cout << " ";
    }
    cout << yytext[0];
    cout << "@";
    BEGIN (LINK_INITIAL);
    REJECT;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "fisierTest.l"
{
    //cout << "459";
    ECHO;
    cout << "\n";
    BEGIN (SKIP_END_LINK_INITIAL);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "fisierTest.l"
{
    BEGIN(INITIAL);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "fisierTest.l"
{
    cout << yytext[1] << yytext[0] << yytext + 2;
    BEGIN (LINK_PARA);
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 67 "fisierTest.l"
{
    cout << yytext[0];
    cout << "@";
    BEGIN (LINK_PARA);
    REJECT;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 73 "fisierTest.l"
{
    ECHO;
    BEGIN (SKIP_END_LINK_PARAGRAPH);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "fisierTest.l"
{
    BEGIN(PARAGRAPH);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "fisierTest.l"
{
    cout << yytext[1] << yytext[0] << yytext + 2;
    BEGIN (LINK_IMP);
}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 85 "fisierTest.l"
{
    cout << yytext[0];
    cout << "@";
    BEGIN (LINK_IMP);
    REJECT;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "fisierTest.l"
{
    ECHO;
    //cout << "\n";
    BEGIN (SKIP_END_LINK_IMPORTANT);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "fisierTest.l"
{
    BEGIN(IMPORTANT);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 100 "fisierTest.l"
{
    cout << yytext[1] << yytext[0] << yytext + 2;
    BEGIN (LINK_LIST);
}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 104 "fisierTest.l"
{
    cout << yytext[0];
    cout << "@";
    BEGIN (LINK_LIST);
    REJECT;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "fisierTest.l"
{
    ECHO;
    cout << "\n";
    BEGIN (SKIP_END_LINK_LIST);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 115 "fisierTest.l"
{
    BEGIN(LIST);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 119 "fisierTest.l"
{
    cout << yytext[1] << yytext[0] << yytext + 2;
    BEGIN (LINK_LIST_IMP);
}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 123 "fisierTest.l"
{
    cout << yytext[0];
    cout << "@";
    BEGIN (LINK_LIST_IMP);
    REJECT;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 129 "fisierTest.l"
{
    ECHO;
    //cout << "\n";
    BEGIN (SKIP_END_LINK_LIST_IMPORTANT);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 134 "fisierTest.l"
{
    BEGIN(LIST_IMPORTANT);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 137 "fisierTest.l"
{
    ECHO;
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 140 "fisierTest.l"
{
    //cout << "801";
    cout << " ";
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 144 "fisierTest.l"
{
     count = min(yyleng, 3);
     BEGIN (IDENTATION);
}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 148 "fisierTest.l"
{
    for (int i = 1; i <= 3 * count; i++) {
         cout << " ";
    }
    cout << "[code]\n";
}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 154 "fisierTest.l"
{
    cout << "[code]\n";
}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 157 "fisierTest.l"
{
    //ECHO;
    cout << " [code]";
    unput(yytext[yyleng - 2]);
    unput(yytext[yyleng - 1]);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 163 "fisierTest.l"
{
    for (int i = 1; i <= 3 * (count + 1); i++) {
        cout << " ";
    }
    cout << "\"";
    blockquote = 5;
    BEGIN (QUOTE);
} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 171 "fisierTest.l"
{
    //string word = yytext;
    //cout << "<" << word.substr(2, word.length() - 4) << ">";
    cout << "<";
    yytext[yyleng - 2] = '\0';
    cout << yytext + 2;
    cout << ">";
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 179 "fisierTest.l"
{
    // string word = yytext;
    // cout << "<" << word.substr(1, word.length() - 2) << ">";
    cout << "<";
    yytext[yyleng - 1] = '\0';
    cout << yytext + 1;
    cout << ">";
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 187 "fisierTest.l"
{
    // string word = yytext;
    // cout << " <" << word.substr(2, word.length() - 4) << ">";
    cout << " <";
    yytext[yyleng - 2] = '\0';
    cout << yytext + 2;
    cout << ">";
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 195 "fisierTest.l"
{
    // string word = yytext;
    // cout << " <" << word.substr(1, word.length() - 2) << ">";
    cout << " <";
    yytext[yyleng - 1] = '\0';
    cout << yytext + 1;
    cout << ">";
}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 203 "fisierTest.l"
{
    strcpy(STXTitle, yytext);
    STXTitle[yyleng - 2] = '\0';
    BEGIN (CHECK_TITLE);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 208 "fisierTest.l"
{
    if (blockquote > 0) {
        if (blockquote < 5) {
            cout << " ";
        }
        ECHO;
        blockquote--;
    }
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 217 "fisierTest.l"
{
    if (strlen(STXTitle) == yyleng) {
        count = 1;
        for (int i = 1; i <= 3 * count; ++i) {
            cout << " ";
        }
        cout << "+ ";
        cout << STXTitle;
        cout << "\n";
        BEGIN (INITIAL);
    } else {
        for (int i = 1; i <= 3 * count; ++i) {
                cout << " ";
        }
        cout << ":" << STXTitle << " ";
        BEGIN (PARAGRAPH);
    }
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 235 "fisierTest.l"
{
    if (strlen(STXTitle) == yyleng) {
        count = 2;
        for (int i = 1; i <= 3 * count; ++i) {
            cout << " ";
        }
        cout << "+ ";
        cout << STXTitle;
        cout << "\n";
        BEGIN (INITIAL);
    } else {
        for (int i = 1; i <= 3 * count; ++i) {
                cout << " ";
        }
        cout << ":" << STXTitle << " ";
        BEGIN (PARAGRAPH);
    }
}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 253 "fisierTest.l"
{
    //ECHO;
    for (int i = 1; i <= 3 * count; ++i) {
         cout << " ";
    }
    cout << ":" << STXTitle << ":\n";
    BEGIN (INITIAL);
}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 261 "fisierTest.l"
{
    for (int i = 1; i <= 3 * count; ++i) {
         cout << " ";
    }
    cout << ":" << STXTitle << " ";
    unput(yytext[yyleng - 1]);
    BEGIN (PARAGRAPH);
}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 269 "fisierTest.l"
{
    cout << "\"\n";
    BEGIN (INITIAL);
} 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 273 "fisierTest.l"
{
    for (int i = 1; i <= 3 * (count + 1); i++) {
        cout << " ";
    }
    cout << "[";
    wordListCounter = 3;
    BEGIN (LIST);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 281 "fisierTest.l"
{
    if (wordListCounter < 3) {
        cout << " ";
    }
    ECHO;
    wordListCounter--;
    if (wordListCounter == 0)
        BEGIN(LIST_IMPORTANT);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 290 "fisierTest.l"
{
    cout << "; ";
    wordListCounter = 3;
    BEGIN (LIST);
}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 295 "fisierTest.l"
{
    cout << "]\n";
    unput(yytext[yyleng - 1]);
    BEGIN(INITIAL);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 301 "fisierTest.l"
{
    for (int i = 1; i <= 3 * count; i++) {
        cout << " ";
    }
    cout << "////////////\n";
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 307 "fisierTest.l"
{
    for (int i = 1; i <= 3 * count; ++i) {
         cout << " ";
    }
    cout << ":";
    ECHO;
    BEGIN (PARAGRAPH);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 315 "fisierTest.l"
{
    for (int i = 1; i <= 3 * count; ++i) {
         cout << " ";
    }
    cout << "+";
    ECHO;
    cout << "\n";
    BEGIN (SKIP_ATX_ENDING);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 324 "fisierTest.l"
{
    ;
}
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 327 "fisierTest.l"
{
    BEGIN (INITIAL);
}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 330 "fisierTest.l"
{
    cout << " ";
}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 333 "fisierTest.l"
{
    cout << ":\n";
    BEGIN (INITIAL);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 337 "fisierTest.l"
{
    BEGIN (IMPORTANT);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 340 "fisierTest.l"
{
    ECHO;
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 343 "fisierTest.l"
{
    cout << ":\n";
    BEGIN (INITIAL);
}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 348 "fisierTest.l"
{
    ;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 351 "fisierTest.l"
ECHO;
	YY_BREAK
#line 1662 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(IDENTATION):
			case YY_STATE_EOF(PARAGRAPH):
			case YY_STATE_EOF(IMPORTANT):
			case YY_STATE_EOF(QUOTE):
			case YY_STATE_EOF(NOT_FIRST_WORD):
			case YY_STATE_EOF(CHECK_TITLE):
			case YY_STATE_EOF(LIST):
			case YY_STATE_EOF(LIST_IMPORTANT):
			case YY_STATE_EOF(CHECK_LINK):
			case YY_STATE_EOF(SKIP_ATX_ENDING):
			case YY_STATE_EOF(LINK_PARA):
			case YY_STATE_EOF(LINK_IMP):
			case YY_STATE_EOF(LINK_LIST):
			case YY_STATE_EOF(LINK_LIST_IMP):
			case YY_STATE_EOF(LINK_INITIAL):
			case YY_STATE_EOF(SKIP_END_LINK_PARAGRAPH):
			case YY_STATE_EOF(SKIP_END_LINK_LIST):
			case YY_STATE_EOF(SKIP_END_LINK_IMPORTANT):
			case YY_STATE_EOF(SKIP_END_LINK_LIST_IMPORTANT):
			case YY_STATE_EOF(SKIP_END_LINK_INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 320 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 320 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 319);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 351 "fisierTest.l"


int main(int argc, char* argv[]) {
    if (argc < 2) {
        cerr << "Error: missing input file" << endl;
        return 1;
    }
    FILE *infile = fopen(argv[1], "r");
    yyin = infile;
    yylex();
    fclose(infile);
    return 0;
}

